service: api-management

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - apigateway:GET
        - apigateway:POST
      Resource:
        - arn:aws:apigateway:${self:provider.region}::/*
  apiGateway:
    apiKeys:
      - free: ${file(./default-customers.js):private}
      - paid:
        - myPaidKey
        - paidUser@example.com
    usagePlan: 
      - free:
          quota:
            limit: 5
            period: MONTH
          throttle:
            burstLimit: 1
            rateLimit: 1
      - paid:
          quota:
            limit: 1000
            period: DAY
          throttle:
            burstLimit: 16
            rateLimit: 50

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true
  getUsage:
    handler: handler.usage
    events:
      - http:
          path: getUsage
          method: get
  getUsagePlans:
    handler: handler.usagePlans
    events:
      - http:
          path: getUsagePlans
          method: get
  addKey:
    handler: handler.addKey
    events:
      - http:
          path: addKey
          method: get

package:
  excludeDevDependencies: true
